# Generated by Django 5.2 on 2025-04-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="ticker",
            field=models.CharField(default="NULL", max_length=4),
        ),
    ]
