# Generated by Django 5.2 on 2025-04-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0002_stock_ticker"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
